language: node_js
node_js:
- '10'
cache:
  directories:
  - node_modules
branches:
  only:
  - master
install:
- yarn install
- npm run generate
script:
- echo "Skipping tests"
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: dist
  repo: robwkirby/robwkirby.github.io
  target-branch: master
  on:
    branch: master